# Generated by Django 4.2 on 2023-04-30 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('ci_usuario', models.IntegerField(null=True)),
                ('departamento', models.CharField(blank=True, choices=[('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Santa Cruz', 'Santa Cruz'), ('Potosi', 'Potosi'), ('Oruro', 'Oruro'), ('Chuquisaca', 'Chuquisaca'), ('Pando', 'Pando'), ('Beni', 'Beni'), ('Tarija', 'Tarija')], max_length=200, null=True, verbose_name='Departamento')),
                ('nombre_usuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('paterno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Materno')),
                ('cel_usuario', models.IntegerField(null=True)),
                ('cel_usuario2', models.IntegerField(null=True)),
                ('correo', models.CharField(blank=True, max_length=240, null=True, verbose_name='Correo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad')),
                ('imagen_usuario', models.ImageField(blank=True, max_length=200, null=True, upload_to='tesis/', verbose_name='Imagen de perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('superusuario_administrador', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
                ('tipo_usuario', models.IntegerField(blank=True, choices=[(1, 'Maestrante'), (2, 'Docente'), (3, 'Tecnico de Postgrado'), (4, 'Coordonación de investigación'), (5, 'Coordonación de Postgrado'), (6, 'Administrador')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesMaestrante',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('idmaestrante', models.IntegerField(null=True)),
                ('descripcion', models.CharField(blank=True, max_length=220, null=True)),
                ('archivo_documento', models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/actividades/')),
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='CentroActividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('idmaestrante', models.IntegerField(null=True)),
                ('usuario', models.CharField(blank=True, max_length=220, null=True)),
                ('actividad', models.CharField(blank=True, max_length=220, null=True)),
                ('fecha', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'verbose_name': 'Centro_actividad',
                'verbose_name_plural': 'Centro_actividades',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_docente', models.CharField(blank=True, max_length=220, null=True)),
                ('guia', models.BooleanField(default=False)),
                ('tribunal', models.BooleanField(default=False)),
                ('revisor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Docente_Guia',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_docente', models.CharField(blank=True, max_length=220, null=True)),
                ('guia', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente_Guia',
                'verbose_name_plural': 'Docentes_Guias',
            },
        ),
        migrations.CreateModel(
            name='Docente_Revisor',
            fields=[
                ('id_revisor', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_docente', models.CharField(blank=True, max_length=220, null=True)),
                ('revisor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente_Revisor',
                'verbose_name_plural': 'Docentes_Revisores',
            },
        ),
        migrations.CreateModel(
            name='TecnicoPostgrado',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.CreateModel(
            name='Maestrante',
            fields=[
                ('id_maestrante', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_maestrante', models.CharField(blank=True, max_length=220, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=220, null=True)),
                ('archivo_borrador', models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/actividades/borrador/')),
                ('archivo_documento', models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/actividades/')),
                ('avance_tesis', models.IntegerField(null=True)),
                ('tema_tesis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tema de Tesis')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.docente_guia')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.docente_revisor')),
                ('tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.docente')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestrante',
                'verbose_name_plural': 'Maestrantes',
            },
        ),
        migrations.CreateModel(
            name='CoordinacionPostgrado',
            fields=[
                ('id_coordinacion_postgrado', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinacion Postgrado',
                'verbose_name_plural': 'Coordinaciones Postgrado',
            },
        ),
        migrations.CreateModel(
            name='CoordinacionInvestigacion',
            fields=[
                ('id_coordinacion_investigacion', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinacion Investigacion',
                'verbose_name_plural': 'Coordinaciones Investigacion',
            },
        ),
    ]
