# Generated by Django 4.2 on 2023-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrante',
            name='fecha_sustentacio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
