# Generated by Django 4.2 on 2023-04-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_maestrante_fecha_sustentacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestrante',
            old_name='fecha_sustentacio',
            new_name='fecha_sustentacion',
        ),
    ]
