# Generated by Django 4.2 on 2023-05-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_fecha_sustentacio_maestrante_fecha_sustentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrante',
            name='hora_sustentacion',
            field=models.Field(blank=True, null=True),
        ),
    ]
