# Generated by Django 4.2 on 2023-05-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_maestrante_hora_sustentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestrante',
            name='hora_sustentacion',
        ),
    ]
