# Generated by Django 4.2 on 2023-05-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_maestrante_fecha_sustentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrante',
            name='hora_sustentacio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
