# Generated by Django 4.2 on 2023-05-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_maestrante_hora_sustentacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestrante',
            old_name='hora_sustentacio',
            new_name='hora_sustentacion',
        ),
    ]
