# Generated by Django 4.2 on 2023-05-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_rename_hora_sustentacio_maestrante_hora_sustentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestrante',
            name='hora_sustentacion',
        ),
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_sustentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
