# Generated by Django 4.2 on 2023-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_maestrante_procedencia_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestrante',
            name='procedencia_tema',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
