# Generated by Django 4.2.1 on 2023-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_maestrante_procedencia_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id_cronograma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=220, null=True)),
                ('fecha_asignado', models.DateField(verbose_name='Fecha de asignación')),
                ('fecha_entregado', models.DateField(verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
            },
        ),
    ]
