# Generated by Django 4.2.1 on 2023-05-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_cronograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='maestrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.maestrante'),
        ),
    ]
