# Generated by Django 4.2.1 on 2023-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_cronograma_maestrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='maestrante',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='idmaestrante',
            field=models.IntegerField(null=True),
        ),
    ]
