# Generated by Django 4.2.1 on 2023-05-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_remove_cronograma_maestrante_cronograma_idmaestrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fecha_asignado',
            field=models.DateField(null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='fecha_entregado',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
    ]
