# Generated by Django 4.2.1 on 2023-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_alter_cronograma_fecha_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrante',
            name='fecha_desarrollo',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='maestrante',
            name='fecha_formulario',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='maestrante',
            name='fecha_perfil',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_sustentacion',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
    ]
