# Generated by Django 4.2.1 on 2023-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_maestrante_fecha_desarrollo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_desarrollo',
            field=models.DateField(null=True, verbose_name='Desarrollo de la investigación'),
        ),
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_formulario',
            field=models.DateField(null=True, verbose_name='Fecha de entrega de formulario de habilitación'),
        ),
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_perfil',
            field=models.DateField(null=True, verbose_name='Fecha de entrega de perfil de Tesis'),
        ),
        migrations.AlterField(
            model_name='maestrante',
            name='fecha_sustentacion',
            field=models.DateField(null=True, verbose_name='Acto de sustentación de tema de Tesis'),
        ),
    ]
