# Generated by Django 4.2.1 on 2023-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_alter_maestrante_fecha_desarrollo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrante',
            name='hora_sustentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
